services:
  - type: web
    name: remotion-video-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: video-storage
      mountPath: /app/output
      sizeGB: 2